[gcp_service_account]
type = "service_account"
project_id = "ardent-rush-464015-t6"
private_key_id = "00bee9d1f10f632ba203f8bdeeed5d53b9bc6e6c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDCyGJjhMiLgqTt
yAaYDZ/K6oa+4h7Y66W2hGNhBPFp/fRhm7G47ljVKYCAT56QEarWQMzx3X7HEIUT
i3tu9FdTEOf9ngUdc4iVSfeai/uapEyotsC9KXZoWaOLR9wVsH9xFLvoiX24j81a
e8ulkMv6bE2x/lhG896j1m0RHGK5zDYHmCZUgZYX+Pln6ZIWugrXcwDdzKT8TR6E
3hpF0nXIe0o1Bfjj4+eyPZP62wkDhO2yf5j/wp9F1j6hbYfJ5qV0xKnKG2STRnvR
iC/2d3ThciRYe4MjHGIs7mGgBItYB+M49cIum3vH9Ws5mzcj66/B2GrJ7Ies9xHe
q1KObAB5AgMBAAECggEAQz4LHUELPIJC7qV1hUt6xQHWt5H3RTqAkDQ+3JDoyIb3
tTSbE3UQ7LGxn1odKq42tFVViw/EgvM0ha1K1OB8PvxgokDJkkO+vI727/7wQpAC
uOGyQvtL2bVMTLpng4NVU5PtVNcWND9MjLac9JC6oj5+Sfq8ve3Vh+jv6Q7MFEiM
RrU0H/zMfYbOv9xYVR/wX7qTRgpruGO8tXlUiP1K2CBsDTqSMRSrMDVErhPmcLyr
slL1ycJ22sqsWvKsoC/Z3FFCd+8Q1oV2C3TsF8+UcJ6VZByBY4T55CzwuKdu91sQ
qJY9QBK9QSCz9Jmi42wQ5kMmcT7R7P+aZ+CHZDd5OwKBgQD+Zw+ooR0E6di4T8Ww
18FDd7b8oFjie9tZ2qFygJrapOG7sLQce9xbRMjCPPsLtDZAMk3q2Rr1UzrDcftK
nwsOgdWhwugHWGbyQJmBSi7hkdQIeD9tuPm29yRxfMxMntBIUoxg+aGlqSp9DXRq
/SvzS/x61SYd73tw4Q/rUkn7zwKBgQDEAXzGq4vwQI+JK4WfrjsTCtCPKSOmrgz4
urYcvL/wTbev3dr02Gyz/hCNHH3RoymsF5J/Strejf4YzHAtwfpN21LBHSEJQ8lB
zmh0oRLpEP/MWztTVij3eP3TLOMDHKeQFjDrO0GGjbRWtEcS+OrayXdh/djK59Lu
n84XmJFpNwKBgQC6apzPzVdtXUngLRxIrKDCpnug/IKFW4rtecZqGBDg/IcouKAS
azSacHnH01WGSwSh3/q2h2Y4tEdQJjqkgIxikgMQKLlLgJzXET0qv0hBJFHB7xNT
fIMHbmv2+SLfVlR7WnnhKasosCAhSHWxXFkTS+/ztjLbJrxGh7TZlBAAgwKBgF1b
VAIQjTumlHdCKogO5YZBXWsCrj9ioT0LOVhgso8ThU0Xv4VlXAkzFtEPZAIo091q
8NT+Y1cjjIZlQX0Z6k2RDE58wFJ4XfChDnGWkro95YiBX7Vm0WZl04f01j+SM2FW
oIA6HhCnh+DQRxYLR1lkIh+jV9H1LyuHJBNrEL9rAoGBAOPOnTX9fDTywu1r/CdZ
iEtChMPZnJ/yEMqws4Plizgjx0XD2fJ6AT3LqVy3StvH5Sixe99PVbRqhttt1Cth
osAfQJQsBfaEmLcEfHfAbDoNgV9zJ8MLmDCO4Li6YQt30OuqF8jlCx4U0YXIM/MJ
v0PEn5zDY/MqMygEj40OvLqL
-----END PRIVATE KEY-----"""
client_email = "zinath-quiz@ardent-rush-464015-t6.iam.gserviceaccount.com"
client_id = "112721970356166803980"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/zinath-quiz%40ardent-rush-464015-t6.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
